### ISSUE TITLE
Add JS Editors section?

### ISSUE THREAD

**Issue by Nothing-Works** [bestofjs/bestofjs-webui#72]

**Comment by michaelrambeau** [comment]
Hello Andy @Nothing-Works 

There is already a category called "Rich Text Editors": https://bestofjs.org/tags/rich-text-editor

Is it what you are looking for?

**Comment by Nothing-Works** [comment]
@michaelrambeau  Yes! sorry I did not find at first glance. I was looking at E.... section.

**Comment by michaelrambeau** [comment]
Don't be sorry @Nothing-Works because I think that it's a problem in _Best of JavaScript_ application: there are lot of tags (150) and it's not easy to find them.

I think we should provide a way to search for tags, using a "autocomplete" feature.
In your case, by entering "editor" you would have found the tag "Rich Text Editor".

Let me know if it makes sense.
Thank you for your feedback!

**Comment by Nothing-Works** [comment]
@michaelrambeau yes that's a good idea I think, and I think [algolia](https://www.algolia.com/) is very good. I believe it's free for open source projects.

**Comment by michaelrambeau** [comment]
@Nothing-Works I will try to improve that point and ask you to check when it's online, thank you again Andy!

**Comment by Nothing-Works** [comment]
@michaelrambeau Thank you! thank you for your time for this awesome library. Otherwise, I will be lost in the "gigantic" JS ecosystem.
