### ISSUE TITLE
Add Embla Carousel React

### ISSUE THREAD

**Issue by davidcetinkaya** [bestofjs/bestofjs-webui#82]
Hi Michael (@michaelrambeau)!

I love the new BestOfJS design and UI, great work 👍. I'd like to add [embla-carousel-react](https://github.com/davidcetinkaya/embla-carousel-react) to the BestOfJS list. It's:

> A tiny React.js wrapper for [Embla Carousel](https://github.com/davidcetinkaya/embla-carousel).

Thank you in advance and have a nice one!

Cheers,
David

**Comment by michaelrambeau** [comment]
Hello David,
Thank you for your comments about the latest changes, there are still a lot things to do, starting with a better home page.

OK, I understand your point of view, _Embla Carousel React_, will be available, but to be honest, I feel it's not totally right because _Embla Carousel_ and _Embla Carousel React_ are not really 2 different projects, they should belong to the same entity. Both projects have the same home page so they are really "connected".

We have already had this discussion but it could be nice to have a single repo in the future.
Now, from the developer point of view, if you make a change that impacts the 2 projects you have to publish changes to 2 different repos at the same time.
From the user point of view, you have to switch to 2 different repos to get the documentation.
Same problem about where to create an issue: you have to figure out if it's a problem in the core package or in the React package.
For Pull Requests, you have to coordinate 2 processes in the same time.

A lot of projects have solved this issue using the concept of "mono-repo", a single repo in GitHub split into multiples packages.

Actually we had a discussion about a feature to be see the packages that belong to a mono-repo in _Best of JavaScript_: https://github.com/michaelrambeau/bestofjs/issues/297#issuecomment-563382980

FYI, for my projects I'm thinking about using [Yarn workspaces](https://yarnpkg.com/en/docs/cli/workspaces#search) but there are other solutions: https://bestofjs.org/projects?tags=monorepo

An other idea: maybe the simplest solution would be to restore the ability of adding "links" to projects.

Anyway I will tell you when _Embla Carousel React_ is available on _Best of JavaScript_, these are only ideas to be discussed.

**Comment by davidcetinkaya** [comment]
Hello again @michaelrambeau,

Thinking about it, you're right and I agree. It's basically the same project so let's skip this process. Thank you for your attention 👍!

Best,
David

**Comment by michaelrambeau** [comment]
Don't misunderstand me David @davidcetinkaya I really want to help you promote _Embla_, your request was accepted, it will be online in 24 hours.

We will adjust things when we both make progress (when _Best of JS handles mono-repos packages and when your project structure changes), no worries 😄

**Comment by davidcetinkaya** [comment]
No worries Michael, and no hard feelings! It's just that you convinced me 🙂. Thinking twice, the react package will be redundant so let's not do anything about it for now 👍.

**Comment by michaelrambeau** [comment]
Hello David! @davidcetinkaya 
It's online, search for "Embla" and you will find 2 occurrences.
Is it OK?
At least until we provide a way to link several NPM packages from a single project?
Or if you prefer I can remove it, waiting for the "multi-package" feature? As you want 😃 
It's just that I'm afraid that other package authors ask me to create several entries of for all variants of their projects!

**Comment by davidcetinkaya** [comment]
Hi Michael @michaelrambeau,
Thank you for your efforts 😄. You convinced me before and I very much agree with your reasoning so I'd prefer if you could remove it if that's ok with you? Sorry if I caused any trouble. It's pretty much the same project so it feels kind of redundant 👍.

Best,
David
