### ISSUE TITLE
Add a timeline with projects by date of creation

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#94]
It could be nice to add a timeline that shows the most significant projects by date of creation, over the last 10 years.

I'm sharing the first draft. It's limited to the "featured" projects
The oldest projects are from 2008! (_Raphael_ and _Jasmine_)

https://bestofjs-git-develop.bestofjs.now.sh/timeline

<img width="975" alt="image" src="https://user-images.githubusercontent.com/5546996/87242664-c68d9880-c469-11ea-9c14-4fd7bde8b87d.png">

**Comment by michaelrambeau** [comment]
## Using a vertical timeline? Some examples

https://codyhouse.co/demo/vertical-timeline/index.html

![image](https://user-images.githubusercontent.com/5546996/87306234-b1d8ff80-c552-11ea-8650-f9bf429f83d7.png)

https://www.florin-pop.com/blog/2019/04/how-to-create-a-timeline-with-react/

https://www.florin-pop.com/timeline

![image](https://user-images.githubusercontent.com/5546996/87306425-f82e5e80-c552-11ea-9025-27dc5c395efd.png)

**Comment by davidcetinkaya** [comment]
Hello Michael (@michaelrambeau),
As requested in issue #93, here’s my opinion: 

I’m going to vote for the [horizontal timeline](https://github.com/bestofjs/bestofjs-webui/issues/94#issue-655361180) with the project logos, because I think you get a nice overview of all significant projects in a couple of seconds. I assume that most developers recognize many of these logos instantly.

The vertical timeline requires a lot of scrolling and don’t provide the same overview. Sure, the vertical timeline allows for some related content for each project, but I’m thinking that this can be solved with the horizontal timeline too. One way to do it would be to show a popover with related info when you click on a logo on the timeline.

I look forward to this feature. Let me know when you have a draft or similar 🙂.

Best
David

**Comment by michaelrambeau** [comment]
## Using a horizontal timeline? 

Thank you for the feedback @davidcetinkaya 
So you think using a horizontal time like the one provided by https://timeline.knightlab.com/ would be better?

![image](https://user-images.githubusercontent.com/5546996/87361874-1ffbe180-c5a8-11ea-908e-0f1b39a134de.png)

Instead of a vertical scrolling, I suppose there would be a horizontal scrolling or maybe a navigation "by slides" (you are a carousel author David, aren't you? 😉 ) like in the _TimelineJS_ project: https://timeline.knightlab.com/
Each year could have its own slide and we could write a short story.
So it's more about storytelling, I guess

An other of example of project we could use: http://twitter.github.io/labella.js/

![image](https://user-images.githubusercontent.com/5546996/87361258-c6df7e00-c5a6-11ea-9fa3-a81ac1cb8137.png)

**Comment by AlgusDark** [comment]
I also vote for the horizontal timeline. Something that could work, aside from the sliced timeline with navigation, I think that there could be sidebar information that you could pull if you don't want to see the timeline, something like what you have.

I think this feature is very interesting.

**Comment by michaelrambeau** [comment]
## Iteration number 2

This time it’s more about storytelling: picking 20 projects from 2006 to 2020, from _jQuery_ to _Rome_.

https://bestofjs-git-develop.bestofjs.now.sh/timeline

![image](https://user-images.githubusercontent.com/5546996/89356332-7916eb00-d6f8-11ea-83d8-8dbebf1ac039.png)

**Comment by davidcetinkaya** [comment]
Great work @michaelrambeau, I like it a lot! Very easy to follow. I know I voted for a horizontal timeline but this one may have changed my mind 😉.

Just a small implementation detail. I know that this is a draft but in case you haven’t noticed: While the information boxes are sliding in, you’re able to scroll sideways. I tested this on mobile and I assume that this isn’t intentional. The wrapper needs overflow hidden to prevent this.

**Comment by michaelrambeau** [comment]
Thank you David, I didn't notice the problem so your feedback is very useful!
Could you reload the page and confirm that it works better after the quick fix I applied?

Thinking more, there may be a similar problem in the top page, because of the sliding effect applied to the "featured projects", sometimes I can see horizontal scrollbars?

**Comment by davidcetinkaya** [comment]
I’m glad it helped Michael @michaelrambeau. The horizontal scroll bar is gone on the [timeline page](https://bestofjs-git-develop.bestofjs.now.sh/timeline) after your fix 👍🏻.

> Thinking more, there may be a similar problem in the top page, because of the sliding effect applied to the "featured projects", sometimes I can see horizontal scrollbars?

Sorry, I’m not sure what you mean 😕?

**Comment by michaelrambeau** [comment]
Sorry for my poor explanation @davidcetinkaya I was talking about the following feature in the "Top page":

![image](https://user-images.githubusercontent.com/5546996/89603470-2a0db900-d8a4-11ea-95ce-d1c15e0aab77.png)

Sometimes I can see horizontal scrollbars while logos are sliding, on Firefox, it could be a similar problem.
But it's out of topic, sorry for the confusion!

**Comment by davidcetinkaya** [comment]
@michaelrambeau no worries. Would you mind sharing a link to the page that you’re mentioning? I can take a look if the issue is present there.

**Comment by michaelrambeau** [comment]
@davidcetinkaya  The "featured projects" is only available on desktop screens, this is why you couldn't find it on the top page (`/` path), I should make it available to all users! 😅

**Comment by davidcetinkaya** [comment]
@michaelrambeau ah, I see. I’ll take a look at it when I have access to my laptop and let you know if the same issue is present on the top page.

**Comment by davidcetinkaya** [comment]
Hello Michael @michaelrambeau,

I can't see the overflow issue on the top route `/`. As far as I can see, the featured projects animate with opacity only. They don't slide in like the timeline 🙂.

Kindly,
David

**Comment by michaelrambeau** [comment]
The timeline was released on 2020-08-13 and we got feedback: #97 

Post on HackerNews: https://news.ycombinator.com/item?id=24142462

**Comment by davidcetinkaya** [comment]
Nicely done @michaelrambeau!
