### ISSUE TITLE
why not add ember to https://bestofjs.org/timeline

### ISSUE THREAD

**Issue by NullVoxPopuli** [bestofjs/bestofjs-webui#97]
since ember is largely responsible for
- es clasess
- import syntax
- decorators
- modern JS in general

ember has been involved with TC39 from the very early days

**Comment by michaelrambeau** [comment]
Hello @NullVoxPopuli 
Thank you for your feedback!
OK a new version has been released, since we wanted a total count of 20 projects I removed Angular 2 (since we have already Angular 1)

> Vox populi, vox dei

... as they used to say in Rome (the Empire era, not the front-end tooling project!)

Could you check the result?

![image](https://user-images.githubusercontent.com/5546996/90198431-950f4080-de0c-11ea-9b81-d31a0d4d2524.png)

**Comment by NullVoxPopuli** [comment]
Beautiful 🥰

**Comment by BBlackwo** [comment]
Another way Ember influenced frontend development was through the Ember CLI. The Angular CLI was heavily influenced by it and even borrowed code from it initially. Probably other CLIs too such as the vue-cli and create-react-app
